/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    CaptchaInput: typeof import('./src/components/CaptchaInput.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
  }
}
