/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index" |
  "/pages/login/index" |
  "/pages/login-demo/index" |
  "/pages/profile/edit" |
  "/pages/profile/index" |
  "/pages/qbank-detail/favorites" |
  "/pages/qbank-detail/index" |
  "/pages/qbank-detail/note-detail" |
  "/pages/qbank-detail/notes" |
  "/pages/qbank-detail/quiz-history" |
  "/pages/qbank-detail/wrong-questions" |
  "/pages/question-bank/index" |
  "/pages/quiz/index" |
  "/pages/register/index" |
  "/pages/test-auth/index" |
  "/pages/quiz/components/QuestionDrawerList";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/question-bank/index" | "/pages/profile/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
